### ISSUE TITLE
Log files need cleaning up

### ISSUE THREAD

**Issue by sjparkinson** [whitesource/npm-plugin#16]
We're adding whitesource to a number of FT projects using Node.js.

When running `whitesource run` I find a number of log files are generated in the root of the project.

I don't see any reason for these files to exist. It'd be good to either not create them in the first place, or at least make sure they are cleaned up after running.

I get the feeling they are for debugging, but most of the time no one is going to need or want them.

**Comment by AsafSavichWs** [comment]
The current version contains a fix.
There is a new flag in whitesource.config.json file called "debugMode".
Only when this flag is set to true, you will see all output files.

Thanks for bringing this to our attention.
