### ISSUE TITLE
Fail on vulnerability

### ISSUE THREAD

**Issue by sjparkinson** [whitesource/npm-plugin#17]
When running `whitesource run` I expected a non-zero exit code if any vulnerabilities were found.

Currently it's just a tool for reporting into whitesource, but I can't use it as part of our CI process to ensure vulnerabilities don't get deployed!

**Comment by matthew-andrews** [comment]
the [documentation](http://docs.whitesourcesoftware.com/display/serviceDocs/NPM+plugin) doesn't mention this (@whitesource-people please fix this) but this is actually possible.  i found an option whilst digging through the code: it's `failOnError`. 

financial-times developers can see how i've implemented it here:-
https://github.com/Financial-Times/di2-whitesource/pull/4/files

**Comment by AsafSavichWs** [comment]
Yeah,
as @matthew-andrews  as mentioned there is a flag called `failOnError` you can use.
In addition, we have updated our documentation, so you could see all possible flags.
https://whitesource.atlassian.net/wiki/spaces/WD/pages/34209870/NPM+Plugin

Thanks!
