### ISSUE TITLE
“env: node\r: No such file or directory” prevents whitesource from executing

### ISSUE THREAD

**Issue by matthew-andrews** [whitesource/npm-plugin#19]
The executable won't execute on *nix systems (Linux/OSX) when installed with an NPM version prior to v5.4.0.  I see this issue both locally and in CI (CircleCI).

I think the issue is that y'all have used Windows to author the file containing the shebang: https://github.com/whitesource/npm-plugin/blob/master/bin/whitesource.js.

I guess the simplest fixed would be to commit with Unix line-endings and re-publish to NPM.

---

I believe the issue was fixed in NPM in v5.4.0 — https://github.com/npm/npm/releases/tag/v5.4.0.

> [0ef320cb4](https://github.com/npm/npm/commit/0ef320cb40222693b7367b97c60ddffabc2d58c5) [#16634](https://github.com/npm/npm/pull/16634) Convert any bin script with a shbang a the start to Unix line-endings. (These sorts of scripts are not compatible with Windows line-endings even on Windows.) (@ScottFreeCode)

**Comment by AsafSavichWs** [comment]
Hi Mathew,

What version of the WhiteSource NPM plugin were you using?
We are aware that this issue exists in V1.0.8 but has been fixed in current version (V1.0.9).

If this keeps happening, please provide also your node and npm versions.
Can you please confirm?

**Comment by matthew-andrews** [comment]
Hi!

NPM version 3.10.10
Node version v6.11.5
White Source NPM version v1.0.9

If you download the v1.0.9 `.tar.gz` from NPM's registry directly and look inside you can see it's not the same as what's in `master` at the moment:-
https://registry.npmjs.org/whitesource/-/whitesource-1.0.9.tgz

**Comment by smarusa** [comment]
Happens also on 
node 8.6.0
NPM 5.3.0
run on Unix.

**Comment by AsafSavichWs** [comment]
Hi @smarusa & @matthew-andrews ,

We have released a new version (1.1.1), you can either download it from NPM or from the npm registry https://registry.npmjs.org/whitesource/-/whitesource-1.1.1.tgz

This issue is fixed in this version.
Please confirm.
Thanks for your patience

**Comment by matthew-andrews** [comment]
Yes that works, thank you for your help!
