### ISSUE TITLE
Whitesource fails on npm audit

### ISSUE THREAD

**Issue by marikaner** [whitesource/npm-plugin#32]
There is a low vulnerability found by `npm audit` in the braces package, which is an indirect dependency of whitesource (whitesource > findup-sync > micromatch > braces). A simple fix would be to upgrade findup-sync to a higher version.

**Comment by akirilyuk** [comment]
Hi, can someone please take care of this issue?

**Comment by mixellent** [comment]
@marikaner @akirilyuk thanks for reporting this. Please note that this issue has now been resolved. You can fetch the latest version  (19.2.1-1) of the npm-plugin here: https://www.npmjs.com/package/whitesource.

**Comment by akirilyuk** [comment]
@mixellent Thank you ❤️
