### ISSUE TITLE
Security vulnerability in this project

### ISSUE THREAD

**Issue by JakeChampion** [whitesource/npm-plugin#7]
```
warning whitesource > glob > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

Hopefully there is a newer version of glob which has the fixed version of minimatch!

**Comment by AsafSavichWs** [comment]
Hi Jake,
We have upgraded the relevant packages and now the vulnerable packages are gone.
Thanks for letting us know,
Asaf.
